### ISSUE TITLE
Reference shared library from dsl

### ISSUE THREAD

**Issue by Kobus-Smit** [ngs-doo/revenj#100]
How do I reference SharedLib in this dsl? 

```
aggregate Root {
    implements c# 'SharedLib.IABC';
}
```

> Internal compiler error. Error compiling object model: Error during compilation: 
> Error: The type or namespace name 'SharedLib' could not be found in the global namespace (are you missing an assembly reference?) in global::Test.Root near: SharedLib.IABC
> 

or should I be using
```
server code <#
...
#>;
```

Would be great if Revenj could code gen interfaces for my aggregates into a Interfaces library! https://github.com/ngs-doo/revenj/issues/89#issuecomment-336747678 The mapping between concepts means I don't have to use AgileMapper anymore but still have the ugliness of using [extern alias](https://blogs.msdn.microsoft.com/ansonh/2006/09/27/extern-alias-walkthrough/) because the same type resides in different assemblies. https://github.com/ngs-doo/revenj/issues/89#issue-263355765

**Comment by zapov** [comment]
You need to put dll in the folder where your dependencies are. Then it should be able to compile it.

Did you try my first suggestion? Just having one Model.dll around which is different from each target.
One important use case for DSL Platform is being able to evolve the model without recompiling your app.
Because of that lots of decisions assume how stuff should be used, and therefore changing one Model with another should not break the app (unless they types are incompatible).
That use case did have only a specific target in mind, but if something is not working across targets it might be worth while fixing it instead.

**Comment by Kobus-Smit** [comment]
I have, and I can't get it to compile. Can you please have a peek at [InterfaceTest](https://github.com/Kobus-Smit/revenj-examples/tree/master/InterfaceTest) to see what I'm missing?


> having one Model.dll around which is different from each target

What do mean? How can I have one Model.dll?

I don't really want to use interfaces but how else do I use an aggregate in an assembly that is shared between the client and the service? 
* The shared assembly can't reference the PostgresModel.dll because then the client project can't use it
* it can't reference the ClientModel.dll because then the service can't use it.
* If the shared assembly references the POCOModel.dll then I get 
`The type 'Person' is defined in an assembly that is not referenced. You must add a reference to assembly 'SimpleMapping.DSL.POCO, Version=2018.3.6.1739, Culture=neutral, PublicKeyToken=null'.`
and if I reference it then
`The type 'Person' exists in both 'SimpleMapping.DSL.Client, Version=2018.3.6.1739, Culture=neutral, PublicKeyToken=null' and 'SimpleMapping.DSL.POCO, Version=2018.3.6.1739, Culture=neutral, PublicKeyToken=null'` and then I have to use ugly extern alias to get it to compile.

Please see [SimpleMapping test project](https://github.com/Kobus-Smit/revenj-examples/blob/043110e11b6168e0014f33788f5a64b229314b32/SimpleMapping/Front-end/Src/MainForm.cs#L26)

**Comment by zapov** [comment]
When Revenj Postgres compiles it uses dlls from where you specified (Revenj/Postgres) to pick up dependencies for compilation.
You need to put this interface dll in the same place.
The project compiled after I unchecked POCO (which didn't have dependency folder specified) and I've put InterfaceTest.App.Common.dll into the Back-end\Lib\Revenj\Postgres and Front-end\Lib\Revenj\Client folders

The Visual studio plugin compiles dlls with strong name dependency.
You might have to switch to java console utility or we can change the plugin not to compile it with hard dependency.

**Comment by zapov** [comment]
There are two separate problems. One is that VS plugin creates strong compilation dependency (which I hate since it prevents dll compiled on .NET 4.5 to run on .NET 4.0)
And the other is that yeah, if you reference two different dlls, you need to use external alias.

I'll take a look later more closely, but if you create Model.dll for POCO target and Model.dll for Revenj target, you should be able to get POCO working with Revenj Model.dll
That way you would not need an alias.

But if you shared dll doesn't reference anything (which is the best course of action in this setup) then you should not be having the need to have two dlls.

I did experiment a lot with this years ago and came out with the conclusion that it's probably not worth the effort using shared dlls. This leads to different project setups, where compiled dlls are standalone thing and don't depend on something volatile.

**Comment by Kobus-Smit** [comment]
>  ...probably not worth the effort using shared dlls.

I have code in a common shared assembly that is called from the client side and the server side,
 like [this test project](https://github.com/Kobus-Smit/revenj-examples/blob/043110e11b6168e0014f33788f5a64b229314b32/SimpleMapping/Front-end/Src/MainForm.cs#L26).

I do not want to duplicate and maintain that code in both client and service plugin projects.

> ...if you create Model.dll for POCO target and Model.dll for Revenj target, you should be able to get POCO working with Revenj Model.dll That way you would not need an alias.

I don't understand how the client side code can then use that without the need of an alias?

I've also tried the `implements c# XYZ.IInterface` approach but it does not work with enums.

What could work is if the compiler genned classes with a POCO or DTO suffix in the POCO library and the Client and Revej libraries inherited from those classes. It would mean the libraries have a dependency on the POCO library. 

That way I can freely pass around the DTOs in a shared library etc. without ugly extern aliases and mappings and still have the nice rich client library and Revenj library classes. The extern aliases also confuse ReSharper with red errrors everywhere although the code compiles fine.

**Comment by zapov** [comment]
I'm describing a setup like this:

Multiproject solution
Shared project - references POCO library named Model.dll
Server project - references Server library named Model.dll and Shared project
Client project - references Client library named Model.dll and Shared project

Shared project needs to put CopyToLocal on false for Model.dll dependency

That way Server project will use Shared project and it's own Model.dll which should work in Shared project due to dynamic binding of library.
I just tried that setup and it works (at least for the use case I tried).

**Comment by Kobus-Smit** [comment]
Ah hah, works on my test case as well, thanks @zapov :)
