### ISSUE TITLE
Security in spring boot

### ISSUE THREAD

**Issue by araneta** [ngs-doo/revenj#68]
i want to secure my spring boot but i don't know how to do it, you have a tutorial on this page https://github.com/ngs-doo/revenj/blob/master/tutorials/revenj-tutorial-security-basics.md but its using .net
Thanks

**Comment by zapov** [comment]
I'll look into covering security aspects for Java, but in the meantime you can register custom [permission manager](https://github.com/ngs-doo/revenj/blob/master/java/revenj-core/src/main/java/org/revenj/security/PermissionManager.java)

and implement your own simple stuff there.

Example implementation could look like this:

    static class SpringPermissionManager implements PermissionManager {
        @Override
        public boolean canAccess(String identifier, Principal user) {
            return user != null;
        }
        @Override
        public <T extends org.revenj.patterns.DataSource, S extends T> Query<S> applyFilters(Class<T> manifest, Principal user, Query<S> data) {
            return data;
        }
        @Override
        public <T extends org.revenj.patterns.DataSource, S extends T> List<S> applyFilters(Class<T> manifest, Principal user, List<S> data) {
            return data;
        }
        @Override
        public <T extends org.revenj.patterns.DataSource> Closeable registerFilter(Class<T> manifest, Specification<T> filter, String role, boolean inverse) {
            return null;
        }
    }

and you register it instead of builtin one, eg:

    container = Revenj.setup();
    container.registerAs(new SpringPermissionManager(), PermissionManager.class);

The only issue with this is that principal will be read from HttpServletRequest in: https://github.com/ngs-doo/revenj/blob/master/java/revenj-servlet/src/main/java/org/revenj/server/servlet/Utility.java#L81
but Spring probably just ignores that. So instead of user != null you can write something along the lines of:

    Authentication auth = SecurityContextHolder.getContext().getAuthentication();
    return auth.isAuthenticated();

in canAccess method.

**Comment by araneta** [comment]
Thank you for your quick reply
I have created SpringPermissionManager class and I have updated Application class constructor as like this
public Application() throws IOException {
		container = Revenj.setup();
		container.registerAs(new SpringPermissionManager(), PermissionManager.class);
		RevenjStartup.setup(container);		
		dataSource = container.resolve(DataSource.class);
	}
but i dont know where to put this:
Authentication auth = SecurityContextHolder.getContext().getAuthentication();
return auth.isAuthenticated();

**Comment by zapov** [comment]
in canAccess method of your implementation

**Comment by araneta** [comment]
i got this error 
 cannot find symbol
  symbol:   class context
  location: package org.springframework.security.core

**Comment by araneta** [comment]
ok fixed it

**Comment by zapov** [comment]
I've updated the Spring example with some security related stuff.
So the answer to your question is you secure it the standard Spring way, eg:

    @Configuration
    @EnableWebSecurity
    public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
        @Override
        protected void configure(HttpSecurity http) throws Exception {
            http
                    .authorizeRequests()
                    .antMatchers("/", "/home").permitAll()
                    //allow public access to one of Revenj routes - will be handled by SpringPermissionManager
                    .antMatchers("/Domain.svc/search/*").permitAll()

This was taken from https://spring.io/guides/gs/securing-web/

Since I've opened up public access to Domain.svc/* this will be handled by PermissionManager
In the SpringBoot example it seems Principal is passed, so there is no need for 

    Authentication auth = SecurityContextHolder.getContext().getAuthentication();
    return auth.isAuthenticated();

Try downloading example again: https://github.com/ngs-doo/revenj/tree/master/tutorials/examples
(I've changed the example to use Revenj v1.1.0, but this might not be available on Maven for couple of hours, so don't just copy it over your current working project)

Regards,
Rikard

**Comment by zapov** [comment]
As for what to do next...
Can you be more specific what you are interested in? Security can be implemented in various ways.
If you are within Spring you can fallback to it's security and roles.

If you wish to model the domain and map it to Revenj security, you can find an example here: https://github.com/ngs-doo/revenj/blob/master/csharp/Core/Revenj.Core/Security/DSL/Security.dsl
where implements is used to map into Revenj security interface.
Builtin RevenjPermissionManager can use those models to map values into security behavior... but it's too broad to explain succinctly here.

I'll look into writing such example for Java next week, but if you have some specific questions which you would like to cover let me know so I can include them in the example.

But basically it boils down to you modeling some users/roles and using that info in permission manager (or just passing it to default permission manager).

**Comment by araneta** [comment]
Thank you so much for your explanation. I will try it now

**Comment by araneta** [comment]
i have updated my code, i can compile it but it throws an exception:
Constructor threw exception; nested exception is java.lang.RuntimeException: Invalid revenj.permission settings found: open.
when i run it:
java -jar target/revenj-boot-1.0-SNAPSHOT.jar 
i already added 
revenj.permissions=open
to revenj.properties

**Comment by araneta** [comment]
i have updated the pom and its working 
i want to integrate this dsl https://github.com/ngs-doo/revenj/blob/master/csharp/Core/Revenj.Core/Security/DSL/Security.dsl with spring security but i dont know how to do it because you are using .net in the example
Thanks

**Comment by araneta** [comment]
Could you explain this code
implements server 'Revenj.Security.IUser';
in the root:
root User(Name)
	{
		string(100) Name;
		Role(Name) *Role;
		binary PasswordHash;
		bool IsAllowed;
		implements server 'Revenj.Security.IUser';
	}
Thanks

**Comment by zapov** [comment]
I've updated the example with some security dsl and comments. I also had to fix some issues and upgrade to v1.1.1

**Comment by zapov** [comment]
Did you manage to figure out what you wanted from the latest example?

**Comment by araneta** [comment]
Thanks i have download it and take a look it. i will ask you again if i have some question. Good Job
