### ISSUE TITLE
Submit an Event

### ISSUE THREAD

**Issue by araneta** [ngs-doo/revenj#70]
I have this event
module Inheritance
{
	event ServeTable
    {        
        string Table;
    }
}
and i have tried to submit event using CURL:    
curl -X POST -H "X-Requested-With: XMLHttpRequest" -H "Content-T
ype: application/json" -H "Cache-Control: no-cache" -d '{  
    "Table": "Table1",    
}' "http://localhost:8080/Domain.svc/submit/Inheritance.ServeTable?result=instance"
but i got this result:
{"timestamp":1482557832179,"status":403,"error":"Forbidden","message":"Could not verify the provided CSRF token because your session was not found.","path":"/Domain.svc/submit/Inheritance.ServeTable"}
How do i get this CSRF token?
Thanks

**Comment by zapov** [comment]
Thats because you've used Spring to secure /Domain.svc/submit/* path
Change it from /Domain.svc/search/* to just /Domain.svc/* in security setup

**Comment by araneta** [comment]
yes i already do that:
@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
				.authorizeRequests()
				.antMatchers("/", "/home", "/homex").permitAll()
				//allow public access to one of Revenj routes - will be handled by Revenj PermissionManager
				.antMatchers("/Domain.svc/*").permitAll()
				.anyRequest().authenticated()
				.and()
				.formLogin()
				.loginPage("/login")
				.permitAll()
				.and()
				.logout()
				.permitAll();
	}

**Comment by zapov** [comment]
I will look at it later... but this is not a Revenj message. Something Spring related. I would guess its still intercepting messages.

**Comment by zapov** [comment]
So it seems my comment about public access was wrong.
Access is behind Spring authentication.. and for unauthenticated users you are either redirected to login form or get an error.

I'm not a Spring expert, but if you wish to put Revenj routes behind some other authorization scheme, I guess you should be able to do something along the lines of: http://www.sothawo.com/2015/07/build-a-spring-boot-rest-service-with-basic-authentication-for-several-users/

**Comment by araneta** [comment]
ok thanks i will try that

**Comment by araneta** [comment]
i have added this http.csrf().disable(); in this function: protected void configure(HttpSecurity http) throws Exception {
and i dont get CSRF error again.

**Comment by zapov** [comment]
I've updated the spring boot example with couple of events.
What you wrote should be working.
Revenj will create META-INF/services registration when it finds this annotation.
Check for that in target/classes/META-INF

**Comment by araneta** [comment]
yes there is a file : org.revenj.patterns.DomainEventHandler%3Cjava.util.concurrent.Callable%3CInheritance.ServeTable%3E%3E
with the content: 

hello.events.TestServeTable
but i cant find this dummy text on console: test event

**Comment by araneta** [comment]
ok i will download the sample

**Comment by araneta** [comment]
I have updated the code and post event using:
curl -X POST -H "X-Requested-With: XMLHttpRequest" -H "Content-T
ype: application/json" -H "Cache-Control: no-cache" -d '{
"username": "Table1",
"password": "P@ssw0rd",
}' "http://localhost:8080/Domain.svc/submit/security.RegisterUser?result=instance"
but nothing happen, the data was not saved

**Comment by zapov** [comment]
What response did you get?
Did event get written down in the DB?

**Comment by araneta** [comment]
no response and this table security."UserRegistered" empty. Here is my repo https://github.com/araneta/revenj

**Comment by zapov** [comment]
Your project works the same as mine.
When I do that request I get 302 with Location: http://localhost:8080/login
And then I need to login first because page is behind Spring auth.
After I'm logged in, I need to pass Cookie auth to the Spring (eg: Cookie: JSESSIONID=7EDCE9AAB7198E6E9E346DAD124FC01E)

After that Jackson fails parsing password, since it's a byte[], not a string, so base64 works (eg "YWJj")
And I need to remove the , after the password.

But I don't have curl so I can't reproduce it, but -o out.txt or something similar should work.

Also, I meant if security.RegisterUser table is populated.. since that's what you are submitting.

So to get it working (in a way) add

    http.httpBasic();

to WebSecurityConfig. Then you can submit event with

    POST http://localhost:8080/Domain.svc/submit/security.RegisterUser
    Host: localhost:8080
    Content-Length: 47
    Authorization: Basic YWRtaW46YWRtaW4=

    {
      "username": "Table2",
      "password": "YWJj"
    }

**Comment by araneta** [comment]
I tried to use postman and i got this response
{"timestamp":1482932826527,"status":500,"error":"Internal Server Error","exception":"java.io.IOException","message":"Unexpected end of JSON input","path":"/Domain.svc/submit/security.RegisterUser"}

**Comment by zapov** [comment]
Its telling you that youve sent invalid json. Maybe the content length you provided does not match actual length

**Comment by zapov** [comment]
As for the error response, servlet needs some more love to turn it into user friendly message

**Comment by araneta** [comment]
ok i removed some headers and it works now
POST /Domain.svc/submit/security.RegisterUser HTTP/1.1
Authorization: Basic YWRtaW46YWRtaW4=
Host: localhost:8080
Cookie: JSESSIONID=4EBAB1DC60700E4EAD1219B537411F1E
Cache-Control: no-cache
Postman-Token: 1a2c5055-0a81-d847-a6d4-3ea19085b6db

{
  "username": "Table2",
  "password": "YWJj"
}
return 1
Thanks for help

**Comment by araneta** [comment]
I tried to use JWT from http://www.svlada.com/jwt-token-authentication-with-spring-boot/ with this revenj but it does not work, I can post an event without a token. Could you help me to fix this problem? My repository is https://github.com/araneta/revenj
Thanks

**Comment by zapov** [comment]
I will take a look, but in the meantime I suggest you uncomment the SpringPermissionManager, return true there from `canAccess` and handle whole security setup inside Spring (WebSecurityConfig).

This way you will not wonder is it Revenj or not... and it's a better/easier way to configure it anyway.

**Comment by zapov** [comment]
I took a look and will assume that the problem with your setup is that everything is open by default.
Since this configuration probably acts differently for unauthorized users... you can access /Domain.svc without logging in.
You can fix that by changing `revenj.permissions` to `closed` in revenj.properties file (you might need to add role access for regular users for your events after that as I did inside InitialData.setup)

But again I suggest if you don't need Revenj roles setup... to configure that inside WebSecurityConfig... instead of partly in Revenj and partly in WSC.

**Comment by zapov** [comment]
Ah... I just realized why your setup did not work.
It's because this jwt plugin handles `/Domain.svc/*` differently then the old one.
You need to use `Domain.svc/**` to get it working the way you want.

**Comment by araneta** [comment]
OK Thanks i will update it

**Comment by araneta** [comment]
i have tried your suggestion but it i got this error message:
{"timestamp":1483415823474,"status":401,"error":"Unauthorized","message":"Unauthorized","path":"/Domain.svc/submit/security.RegisterUser"}
by the why may I know how to post an event from Controller?
Thanks

**Comment by zapov** [comment]
Probably the easiest thing is to use DataContext API, eg.

    @Autorwire private DataContext context;

and then

    context.submit(event)

As for the Unathorized message... I thought that was the point... it's now handled by jwt - once you have updated the route to something it recognizes. I assume you need to pass in a correct token before it let's you pass. Also, make sure you have registered the custom SpringPermissionManager... since the example you've used has security* stuff setup only for the administrator... If that is the source of your problem, you can remove that role check in InitialData

**Comment by araneta** [comment]
i got another error: You don't have permissions to access:security.RegisterUser
I think i will post event from controller, its easier. Thanks

**Comment by zapov** [comment]
That error is related to the security setup done in the InitialData
It only allows users with ADMIN role to access security* namespace.

**Comment by zapov** [comment]
But yeah, either use controllers which you know or override the builtin PermissionManager with custom one. You don't get any benefit of the builtin this way.
