### ISSUE TITLE
Download dsl-compiler every compile

### ISSUE THREAD

**Issue by araneta** [ngs-doo/revenj#71]
Why it always download dsl-compiler every time compile the project:
Checking for latest compiler version due to download option
[info] dsl-compiler.exe at latest version (2016-12-22)
is there any way to just compile the code?

**Comment by melezov** [comment]
By default, the compiler is downloaded once into your temporary folder `<tmp>/DSL-Platform/dsl-compiler.exe` and every time you run it, the Maven plugin will check for the latest versions online.

It will not download it "every time you compile", but rather check the release date (it says so in the info - compiler at latest version).

Is this really an issue? If you really want to skip even this check (say you're in offline mode), we could investigate how to make the plugin run the compiler in server mode - this will also make compilation much faster (ms instead of seconds).

**Comment by araneta** [comment]
yes how to skip that?
Thanks

**Comment by zapov** [comment]
You can either put dsl-compiler.exe in your project root or 

    <compiler>path_to_compiler</compiler>

to Maven settings

**Comment by araneta** [comment]
thanks its working, its faster now
