### ISSUE TITLE
call function in the database

### ISSUE THREAD

**Issue by araneta** [ngs-doo/revenj#76]
sorry may be this is out of the context but i found this function in schema:

```
CREATE OR REPLACE FUNCTION university."insert_University"(_inserted university."University_entity"[])
  RETURNS void AS
$BODY$
BEGIN
	INSERT INTO "university"."University" ("ID", "name", "ownerUserID") VALUES(_inserted[1]."ID", _inserted[1]."name", _inserted[1]."ownerUserID");
	
	PERFORM pg_notify('aggregate_roots', 'university.University:Insert:' || array["URI"(_inserted[1])]::TEXT);
END
```

How do i call this function from sql ?

**Comment by zapov** [comment]
You mean how do you call it from JDBC/outside of Revenj?

I don't think it's easy to call it... since you need to construct University_entity tuple somehow.
This specific one you can call as ARRAY[ROW(id, name, user_id)::university."University_entity"]... but when you add some other columns, row arguments will change.
