### ISSUE TITLE
Cast between objects from generated models and preloading aggregates

### ISSUE THREAD

**Issue by Kobus-Smit** [ngs-doo/revenj#89]
Hi Team

I have a situation where I want to call a "Load" IServerService method from my service plugin and it should return to the client a custom object containing an IAggregateRoot object.

The client can then update the aggregate root and send it back by calling the "Save" service plugin method.

The custom object's class is in an assembly shared between the client and the server plugin.

So my shared assembly references the "POCO library" dll
And my client references the "Client library" generated by DSL Platform and also the "POCO library".
And my service plugin references the "Revenj for Postgres" dll and also the "POCO library".

I had to use "extern alias" to use those same types that resides in different assemblies.

1. How do I cast/copy between a POCO object and a Client object 
or between a POCO object and Revenj for Postgress object?
Do I need to manually copy the properties or use Automapper or something?

2. It is probably not correct to use 3 different model dlls?  What is best practise?
But if I for example use the "Revenj for Postgres" dll in my service plugin and also in my WinForms client then I "loose" nice functionality like .Search and .FindAll?

3. How do I send a "preloaded" aggregate object as parameter? My aggregate object has reference properties so it will only lazy load them. I want to send the fully loaded aggregate object to the client to prevent the additional lazy loading server round trips that could be slow because of a bad latency network.
So I call all the reference properties (server side) and then the aggregate object is "preloaded"/"fully hydrated". But it does not seem to serialize the reference properties (because they do not have DataMember attributes?) so I do not receive the full object client side.

Snowflakes and reports work great but they are readonly, so I can't use them as DTOs.

Can you please advise me?

If my questions are not clear enough I can prepare a sample project and send it to you.
Much appreciated.

Regards

**Comment by zapov** [comment]
1) If possible the best way to organize the project would be to reference a Model library. So shared assembly would reference POCO Model library, client would reference Client Model library and so on. 
If that doesn't work then something like Automapper can be used, but that goes against the intent of the usage :)
Yeah, when used from WinForms client it's preferable to use library suited for that (which is not working with the database, but rather calls them over the network).

  3) Ideally aggregates should be self contained, meaning you should use lazy load sparingly and mostly for convenience. But since there are always scenarios when it's better to send more data over the wire there are several ways to deal with it:
     * often the referenced aggregate should be an entity and part of the original aggregate
     * sometimes the referenced aggregate should be a snapshot version of the aggregate (eg, you have an invoice and it references a customer, but it actually references a snapshot of the customer, so it makes sense to have that property as a snapshot)
     * snowflake as you said are often a solution but are not convenient due to read only nature - currently you can copy them to the aggregate at the end - and this is something compiler could certainly help with (it's actually on TODO so it might appear soon)
     * reports are readonly, but you can have collection of aggregates as a parameter within a report... and a collection of other aggregates which would be lazily loaded as another parameter... this would make it convenient to send that report object over the wire... but you would have to deal with manually looking up references from the report instead via lazy load
     * lazy load actually uses specific interface to load up data... you could register your own implementation for that interface and redirect lazy load to some local cache

If you have some example project I can suggest specific C#/DSL snippets which could help.

**Comment by Kobus-Smit** [comment]
Thanks for the detailed reply @zapov.

I've added some example projects at https://github.com/Kobus-Smit/revenj-examples with some explanations in the readme. 

Much appreciated.

**Comment by zapov** [comment]
So for the lazy load problem I would send three objects instead of only one.
So instead of 

    (Submission submission, byte[] inputsTableBytes)

I would send

    (Submission submission, Customer customer, Form form, byte[] inputsTableBytes)

This would make it clear what to use.
If you mind lazy load on the server you can load them in one go via

    var data =
      (from s in context.Query<Submission>()
       from c in context.Query<Customer>()
       from f in context.Query<Form>()
       where s.ID == id
         && c.ID == s.CustomerID
         && f.ID == s.FormID
       select new { s, c, f }).FirstOrDefault();

As for the unknown type, you can use IDomainModel to lookup the actual type and work via generic interfaces. A lot of Revenj server commands work that way.. so you don't need to use DataTable and bytes, but can actually send the appropriate object over the wire. Eg, events are deserialized via Type: https://github.com/ngs-doo/revenj/blob/master/csharp/Plugins/Revenj.Plugins.Rest.Commands/DomainCommands.cs#L393

**Comment by Kobus-Smit** [comment]
Thanks, I've implemented your first suggestion [UseCase1_04_LessRoundTripsSend3ExtraObjects](https://github.com/Kobus-Smit/revenj-examples/tree/master/UseCase1_04_LessRoundTripsSend3ExtraObjects) and it is a solution to the lazy load although if does not feel too elegant to me because of the extra code. Some kindof pre-loading would be nice...

![image](https://user-images.githubusercontent.com/11263864/31322317-45883fda-ace1-11e7-9faa-0deed16923ba.png)

![image](https://user-images.githubusercontent.com/11263864/31322324-59130ddc-ace1-11e7-88e1-0e9f215d8bb2.png)

![image](https://user-images.githubusercontent.com/11263864/31322327-6c040234-ace1-11e7-8048-402ea71575d0.png)


I think a read/write snowflake would result in less code.

**Comment by Kobus-Smit** [comment]
> If you mind lazy load on the server you can load them in one go via
> 
> ```
> var data =
>   (from s in context.Query<Submission>()
>    from c in context.Query<Customer>()
>    from f in context.Query<Form>()
>    where s.ID == id
>      && c.ID == s.CustomerID
>      && f.ID == s.FormID
>    select new { s, c, f }).FirstOrDefault();
> ```

Regarding you one go server side load suggestion, I'm not sure how to use it?
How do I pass the anonymous type back to the client? I would have to create a DTO and map it?

**Comment by Kobus-Smit** [comment]
As a test I've removed the internal setters and compiled the generated source manually.

![image](https://user-images.githubusercontent.com/11263864/31322622-fc60c0f6-ace6-11e7-82cb-b06466228e26.png)

I've added [UseCase1_05_LessRoundTripsWithReadWriteSnowFlake](https://github.com/Kobus-Smit/revenj-examples/tree/master/UseCase1_05_LessRoundTripsWithReadWriteSnowFlake) and it works nice and is less boilerplate code compared to [UseCase1_04_LessRoundTripsSend3ExtraObjects](https://github.com/Kobus-Smit/revenj-examples/tree/master/UseCase1_04_LessRoundTripsSend3ExtraObjects)

@zapov , would it be possible to add an option to generate writable snowflakes?

**Comment by zapov** [comment]
Mutable snowflakes should be rather easy to support, at least for .NET

Writable snowflakes are on TODO, so you can do some specialized optimizations.

What I meant with that query was just to load all the data in one SQL statement. You still need to assign loaded properties onto something which you want to pass along (especially since you use that extra bytes).
An alternative way for that loading (which works outside of .NET) would be to use report concept. Such as:

    report RichSubmission {
      guid id;
      Submission Submission from 'it => it.ID == id';
      Customer Customer from 'it => it.ID == Submission.CustomerID';
      Form Form from 'it => it.ID == Submission.FormID';
      FormGroup Group from 'it => it.ID == Form.GroupID';
    }

and send that RichSubmission.Result over the wire.
Second best alternative to that would be to declare struct with the relevant properties, populate them manually and send that over the wire.

Of course if a snowflake can provide all the relevant info it's much easier to just use that for sending the result. Often it's much better to have different objects for reading/writing API... so while snowflake can cover read scenario it's preferable to use events/commands to do the actual write operation on the server.

If you want to go full meta, server and client concepts do not need to match. Eg, server snowflake can be a struct on the client (which would make it mutable). But unless separate teams maintain the DSL, you probably shouldn't do that because it will bring in more confusion that benefit :(

I have mapping between concepts as TODO for near future and that is something which would remove some of the friction... 

But I'll look this week into adding compiler setting to enable snowflakes to be mutable (I already need something along those lines for events in Scala).

**Comment by Kobus-Smit** [comment]
Thanks again.

It is nice that the RichSubmission report loads all in one SQL statement but I'm not so much concerned with multiple trips between the db and the HTTP service as they would usually be co-located. I want to minimize roundtrips between client and HTTP service because of mentioned latency.

What I do not like about the RichSubmission report is that there is duplication and confusion,
for example the client developer will see RichSubmission.Submission.Customer and RichSubmission.Customer, and he should not use the first mentioned one because it might lazy load...
And the report is also readonly as snowflakes.

I'm still leaning towards mutable snowflakes for now as it is the least boilerplate.

I agree with:

> Often it's much better to have different objects for reading/writing API... so while snowflake can cover read scenario it's preferable to use events/commands to do the actual write operation on the server.

and it will work fine if I have a command with a common/shared DTO that contains only built-in .NET objects but as soon as I want to use my domain classes then I'm back to my original question of how do I map between Client and POCO and Postgres objects... That involves Automapper boilerplate until Revenj can do those mappings :)

**Comment by Kobus-Smit** [comment]
> As for the unknown type, you can use IDomainModel to lookup the actual type and work via generic interfaces. A lot of Revenj server commands work that way.. so you don't need to use DataTable and bytes, but can actually send the appropriate object over the wire. Eg, events are deserialized via Type: 

Thanks I used IDomainModel and Reflection to [create the appropriate object](https://github.com/Kobus-Smit/revenj-examples/blob/6dea41a60094218210c2f912c50a24255455c0f6/UseCase1_06_LessRoundTripsWithReadWriteSnowFlakeAndWithoutDataTables/Back-end/Src/ServerCommand/LoadSubmission.cs#L25), I'm just not sure how to serialize it server-side and deserialize it client-side?

**Comment by zapov** [comment]
You can always model without the explicit references to other aggregates (that's often the preferred way for most DDD practitioners)

So instead of having

    Customer *Customer;

which is a (mostly) shorter version for

    int CustomerID;
    Customer(CustomerID) *Customer;

which includes also an implicit relationship. But if you don't want to have rich reference you can just have relationship

    int CustomerID;
    relationship Customer(CustomerID) Customer;

Which will provide you with FK and will allow navigation over it in snowflakes.

I think in Java version Deprecated is put (by default) on aggregate reference properties... so people are aware they are leaving the root. Scala version requires additional parameters to access that property... so it's obvious something is going on there. I did not yet put anything in the .NET version (but I should, since there is a compiler option to remove that warning).

**Comment by Kobus-Smit** [comment]
Hi @zapov ,

The best solution for me so far (least code, no Automapper etc.) is to use reports as you suggested. Reports are more mutable than snowflakes, at least if you only change top level properties. Deeper properties are not serialized because of lazy loading but I [modified](https://github.com/Kobus-Smit/revenj-examples/blob/31ea1bc6e42e3ff0a620e67e82c8e9e96d493384/UseCase1_07_LessRoundTripsWithReadWriteReports/TempTest/DOTNET_CLIENT/global__UseCase1.Submission.cs#L179) the gen code and then it works fine. Would be really nice if there were a dsl-compiler option for that. And maybe later also some kind of [LazyLoad](https://github.com/Kobus-Smit/revenj-examples/blob/31ea1bc6e42e3ff0a620e67e82c8e9e96d493384/UseCase1_07_LessRoundTripsWithReadWriteReports/TempTest/DOTNET_CLIENT/global__UseCase1.Submission.cs#L193) property (true by default but if false acts more mutable).

I've added example project [UseCase1_07](https://github.com/Kobus-Smit/revenj-examples/tree/master/UseCase1_07_LessRoundTripsWithReadWriteReports) and updated the [readme](https://github.com/Kobus-Smit/revenj-examples). I like that UseCase1_07 has less code than the the previous ones.

Thanks again, I really enjoy using Revenj.

**Comment by zapov** [comment]
I've added compiler option for mutable snowflakes (and it's support for VS). In CLC you can add it via settings=mutable-snowflake and force until it's listed among all settings.
I'm yet to figure out how/if can I upload VS plugin to the marketplace and support VS 2010 :(

As for [DataMember] on properties to other aggregates... I could add that support in the compiler but kind of don't like it. Currently it's easy to reason about boundaries and lazy load and what will happen (as long as you understand some basic rules).

It seems to me that there is maybe a missing feature... such as snapshot - which would put DataMember on that property but it has specialized behavior. I mean, it would be easy just to add preload there and make the code to eagerly load that object... pass it around... but it kind of doesn't feel aligned with the intended usage. Currently there isn't a built in concept of lazy load in the compiler, only references to (which are kind of lazy load). But load patterns are explicitly defined via type system. Conditional eager load doesn't look like a type system feature, but rather as an implementation in the code.

I'll think about this some more, but it seems to me that writable snowflakes (which can narrow down or expand the fields of the aggregate) are probably the missing feature, since that would still follow the rules, allow preloading and ease up on the crud via mutability.

**Comment by Kobus-Smit** [comment]
Yes writable snowflakes would probably be the better solution.

Until then (and for my case where I'm writing the back-end and the front-end) I prefer the [DataMember] on properties to other aggregates because mutable snowflakes still require boilerplate and mapping code to save the changes back to the database.

Speaking of mappings, I again have a situation where I have code that is shared between the client and the service.  For example,

```
  //Client: abc from Client Model library
  CommonMethod1(abc.ToPOCO());

  //Service: abc from Postgres library
  CommonMethod1(abc.ToPOCO());

  //Shared Lib: abc from POCO library
  public static bool CommonMethod1(Abc abc)
  {
  }
```

I'm now using [AgileMapper](https://github.com/AgileObjects/AgileMapper)
```
extern alias common;
using C = common::Module1;
using static AgileObjects.AgileMapper.Mapper;

namespace Aaaa
{
    public static class Mapping
    {
        public static C.Abc ToPOCO(this Abc from) => Map(from).ToANew<C.Abc>();
    }
}
```

How possible would it be to also generate a separate Interfaces assembly? 

```
  //Client: abc from Client Model library, ABC implements IABC
  CommonMethod1(abc);

  //Service: abc from Postgres library, ABC implements IABC
  CommonMethod1(abc);

  //Shared Lib: abc from Interface library
  public static bool CommonMethod1(IAbc abc)
  {
  }
```

Seems that the VS plugin must be upgraded to [VSIX v3](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-migrate-extensibility-projects-to-visual-studio-2017) to support VS 2012 - 2017 and then a new VSIX v1 must be created with support [for VS 2010](https://docs.microsoft.com/en-us/visualstudio/extensibility/faq-2017#what-should-i-do-with-my-extension-that-currently-supports-visual-studio-2010-and-later) (with new GUID and Gallery entry)

**Comment by zapov** [comment]
What you can do in a shared library is define an interface eg IABC and make gen code implement that interface via

    aggregate Root {
        implements c# 'SharedLib.IABC';
    }

Then you can just do the logic for the specified interface in the shared library and let models depend on it.

I'll be adding mapping between concepts soon, that should remove part of your problem.

Tnx, I'll look into those articles. will explore some hacks first before giving up :(

**Comment by Kobus-Smit** [comment]
Looking forward to mapping between concepts and writable snowflakes!

**Comment by zapov** [comment]
I've added partial support for serialization name feature in C#.
To get the behavior you want (data member on reference to another aggregate) you need to explicitly specify serialization name for that reference, eg:

    Customer *Customer { serialization name 'Customer'; }

**Comment by Kobus-Smit** [comment]
Thank you @zapov ! Syntax is a bit verbose but it works.

**Comment by zapov** [comment]
I've added an initial version of the mapping feature (which works in C#). An example would be 

    root Person
    {
      String name;
      List<Int> numbers;
    }
    struct PersonVM
    {
      String name;
      List<Int> numbers;
      has mapping toVM from Person;
    }
    mapping toVM
    {
      identical;
    }

Which would support mapping between different concepts which have **identical** properties.
For snowflakes you don't need the identical keyword, since they are related. Eg:

    root Person
    {
        String name;
        Int age;
        Person? *person;
        Other other;
        has mapping between from PersonInfo;
        has mapping between into PersonInfo;
    }
    entity Other
    {
        int x;
        string s;
    }
    snowflake<Person> PersonInfo
    {
        name;
        age;
        person;
        other.x as ox;
    }
    mapping between;

Let me know if that solves your problem, or you find any issues.

**Comment by Kobus-Smit** [comment]
Fantastic @zapov! 

I've updated my project to use structs and it solved my initial issue. I've deleted lots of unnecessary code. Much simpler now.

I only now noticed that you did mentioned structs [9 Oct](https://github.com/ngs-doo/revenj/issues/89#issuecomment-335062146)  :astonished:
I did not see structs on the dsl-platform.com docs site. I should have checked intellisense better... 

The mapping also works great 👍

Can I buy you a beer or something?!

**Comment by zapov** [comment]
Btw. I just did a breaking change (which I ought to have done from the start). It's now an instance member... which makes it more useful, eg: load aggregate from db, update relevant fields on it.

Also, for maximum dry you can use mixins between concepts so you don't have to repeat members... but this will reduce readability...

I'll keep it on mind next time I'm Down under ;)

**Comment by Kobus-Smit** [comment]
💯
