### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by Kobus-Smit** [ngs-doo/revenj#92]
Does DSL-Platform / Revenj support default values for aggregate properties?

For example when I create a new create a new Customer I want it's IsActive property to default to true.

**Comment by zapov** [comment]
I think this should work:

    bool isActive { default c# 'true'; }

Btw. best way to explore the grammar is to use CTRL + space within the context... eg if you cursor is within a property context that should invoke that specific grammar.

**Comment by Kobus-Smit** [comment]
That works great thanks!

Is this documented somewhere? I've searched dsl-platform.com and github.com/ngs-doo for a while and did not find it.

I've tried Ctrl + Space before and now again and it does nothing here :-(  (VS 2017 v15.4.2)

**Comment by zapov** [comment]
Not sure if it's documented. It seems like a minor thing so it probably isn't.

I just tried it and it works for me... eg:

    aggregate Obj {
      int X { >> CURSOR HERE << }
    }

It works for me if I do it while the cursor is at that location. 
Actually this was fixed in v1.7.3
Previously you had to first have a concept there before autocomplete worked.

**Comment by Kobus-Smit** [comment]
Got it, autocomplete works now that I know I first need to add the two curly braces :+1:
